sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f ./frontend/Dockerfile.dev ./frontend/

script:
  - docker run docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket-name: "elasticbeanstalk-us-east-1-30172668388"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"